
#if !defined(__VERSION_H__)
  #define __VERSION_H__

#define VER_STR_(s) #s
#define VER_STR(s) VER_STR_(s)

/* --- Produktversion --- */
#define FILE_VERSION_MAJOR    0
#define FILE_VERSION_MINOR    0
#define FILE_VERSION_PATCH    18

#define APP_VERSION_MAJOR     FILE_VERSION_MAJOR
#define APP_VERSION_MINOR     FILE_VERSION_MINOR
#define APP_VERSION_PATCH     FILE_VERSION_PATCH

#define VER_COMPANYNAME_STR       "STZ Engineering"
#define VER_FILEDESCRIPTION_STR   "System Info ZX Spectrum Next"
#define VER_FILEVERSION           FILE_VERSION_MAJOR,FILE_VERSION_MINOR,FILE_VERSION_PATCH
#define VER_FILEVERSION_STR       VER_STR(FILE_VERSION_MAJOR) "." VER_STR(FILE_VERSION_MINOR) "." VER_STR(FILE_VERSION_PATCH)

#define VER_INTERNALNAME_STR      "sysinfo"

#define VER_LEGALCOPYRIGHT_STR    "\x7F 2025 " VER_COMPANYNAME_STR
#define VER_ORIGINALFILENAME_STR  VER_INTERNALNAME_STR

#define VER_PRODUCTNAME_STR       "ZXN Tools"
#define VER_PRODUCTVERSION        APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_VERSION_PATCH
#define VER_PRODUCTVERSION_STR    VER_STR(APP_VERSION_MAJOR) "." VER_STR(APP_VERSION_MINOR) "." VER_STR(APP_VERSION_PATCH)

#endif /* __VERSION_H__ */
